# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_name', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='place_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='shipping_cost',
        ),
        migrations.AlterField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_costs',
            field=models.ManyToManyField(related_name='shipping_costs', to='carts.ShippingCost', verbose_name='Shipping Cost'),
        ),
    ]
