# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170726_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-full_price'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
