# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('coefficient', models.DecimalField(decimal_places=4, default=0.0, max_digits=9, verbose_name='Ratio to the dollar')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Currency'),
            preserve_default=False,
        ),
    ]
